//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspect.DesignByContract.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspect.DesignByContract.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ &apos;{0}&apos; ist in mehreren Assemblys definiert. Bitte geben Sie die vollständige Beschreibung des Typs in dem Kontrak an (&apos;Namespace.TypeName&apos;). Liste der doppelten Definitionen:{1} ähnelt.
        /// </summary>
        internal static string ExcAccessToDoubleType {
            get {
                return ResourceManager.GetString("ExcAccessToDoubleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die übergebene Assembly ist nicht definiert. ähnelt.
        /// </summary>
        internal static string ExcAssemblyNull {
            get {
                return ResourceManager.GetString("ExcAssemblyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine passende Methode mit dem Schlüssel &apos; ähnelt.
        /// </summary>
        internal static string ExcCantFindMethodBegin {
            get {
                return ResourceManager.GetString("ExcCantFindMethodBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; gefunden werden. ähnelt.
        /// </summary>
        internal static string ExcCantFindMethodEnd {
            get {
                return ResourceManager.GetString("ExcCantFindMethodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler beim Erzeugen des Kontrakts für das Element &apos;{0}&apos; (Assembly: &apos;{1}&apos;, Namespace: &apos;{2}&apos;, Klasse: &apos;{3}&apos;) aufgetreten. Fehlermeldung aus dem System: {4} ähnelt.
        /// </summary>
        internal static string ExcCompileError {
            get {
                return ResourceManager.GetString("ExcCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Objekt welches mit dem Schlüssel {0} gespeichert wurde ist null. ähnelt.
        /// </summary>
        internal static string ExcContractClassIsNull {
            get {
                return ResourceManager.GetString("ExcContractClassIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es existiert kein IContract Objekt mit dem Schlüssel {0}. ähnelt.
        /// </summary>
        internal static string ExcContractClassNotExist {
            get {
                return ResourceManager.GetString("ExcContractClassNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das übergebene Element ist &apos;null&apos;. ähnelt.
        /// </summary>
        internal static string ExcContractedMemberIsNull {
            get {
                return ResourceManager.GetString("ExcContractedMemberIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der übergebene Kontrakt ist &apos;null&apos; bzw. leer ähnelt.
        /// </summary>
        internal static string ExcContractIsNull {
            get {
                return ResourceManager.GetString("ExcContractIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Liste mit den übergebenen Kontrakten ist Leer. ähnelt.
        /// </summary>
        internal static string ExcContractListIsNull {
            get {
                return ResourceManager.GetString("ExcContractListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Bedingung &apos;{0}&apos; wurde im Element &apos;{1}&apos; nicht erfüllt. ähnelt.
        /// </summary>
        internal static string ExcContractNotValid {
            get {
                return ResourceManager.GetString("ExcContractNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das übergebene Element &apos;{0}&apos; ist nicht vom MemberInfo ähnelt.
        /// </summary>
        internal static string ExcElementisNoMemberInfo {
            get {
                return ResourceManager.GetString("ExcElementisNoMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Objekt element darf nicht &apos;null&apos; sein. ähnelt.
        /// </summary>
        internal static string ExcElementIsNull {
            get {
                return ResourceManager.GetString("ExcElementIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden nicht alle Kontrakte definiert. Bitte tragen sie einen Kontrakt ein oder wählen Sie einen anderen Konstruktor und benutzen ggf. die bennanten Parameter DbcAccessType oder DbcCheckTime. ähnelt.
        /// </summary>
        internal static string ExcEmptyContract {
            get {
                return ResourceManager.GetString("ExcEmptyContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Prüfen eines Kontrakts ist ein unerwarteter Fehler aufgetreten. Der Kontrakt &apos;{0}&apos; für das Element &apos;{1}&apos; konnte nicht geprüft werden. ähnelt.
        /// </summary>
        internal static string ExcErrorInContract {
            get {
                return ResourceManager.GetString("ExcErrorInContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Methode &apos;{0}&apos; kann nicht angegeben werden, da sie &apos;void&apos; zurückgibt. ähnelt.
        /// </summary>
        internal static string ExcMethodIsVoid {
            get {
                return ResourceManager.GetString("ExcMethodIsVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Assembly {0} sind mehr als eine Klasse definiert. Dadurch ist die Assembly nicht gültig. ähnelt.
        /// </summary>
        internal static string ExcMoreClassesInContractAssembly {
            get {
                return ResourceManager.GetString("ExcMoreClassesInContractAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden mehrere Elemente mit dem Namen &apos;{0}&apos; gefunden. ähnelt.
        /// </summary>
        internal static string ExcMorePublicMemberFound {
            get {
                return ResourceManager.GetString("ExcMorePublicMemberFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Typ {0} ist kein Generischer Paramter ähnelt.
        /// </summary>
        internal static string ExcNoGenericParameter {
            get {
                return ResourceManager.GetString("ExcNoGenericParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben keine Kontraktprüfungen für den Lesezugriff angegeben. Bitte Benutzen Sie in diesem Fall einen anderen Konstruktor und übergeben die benannten Paramter DbcAccessType. ähnelt.
        /// </summary>
        internal static string ExcNoGetContracts {
            get {
                return ResourceManager.GetString("ExcNoGetContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung kann auf Eigenschaft &apos;{0}&apos; nicht zugreifen, da eine Get Methode fehlt. ähnelt.
        /// </summary>
        internal static string ExcNoGetMethodAvailable {
            get {
                return ResourceManager.GetString("ExcNoGetMethodAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Assembly {0} ist der zu ladende Typ keine Klasse die von der IContract Schnittstelle ableitet. ähnelt.
        /// </summary>
        internal static string ExcNoIContractClass {
            get {
                return ResourceManager.GetString("ExcNoIContractClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben keine Kontraktprüfungen für den Schreibzugriff angegeben. Bitte Benutzen Sie in diesem Fall einen anderen Konstruktor und übergeben die benannten Paramter DbcAccessType. ähnelt.
        /// </summary>
        internal static string ExcNoSetContracts {
            get {
                return ResourceManager.GetString("ExcNoSetContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der übergebene DbcExceptionType ist keine Ableitung von System.Exception. ähnelt.
        /// </summary>
        internal static string ExcNotValidDbcExceptionType {
            get {
                return ResourceManager.GetString("ExcNotValidDbcExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Apekt Parameter &apos;{0}&apos; kann nicht an Felder definiert werden da ein Feld nur bei Zugriffen (Lese oder Schreibzugriff) den Kontrakt prüfen kann. ähnelt.
        /// </summary>
        internal static string ExcOldAccesNotValidOnField {
            get {
                return ResourceManager.GetString("ExcOldAccesNotValidOnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Apekt-Parameter &apos;{0}&apos; kann nicht in Eintrittskontrakte definiert werden da es zu diesem Zeitpunkt keinen alten Wert gibt. ähnelt.
        /// </summary>
        internal static string ExcOldAccesNotValidOnMethodAndProperty {
            get {
                return ResourceManager.GetString("ExcOldAccesNotValidOnMethodAndProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben lediglich einen Kontrakt definiert für diesen Fall benutzen Sie bitte den Kontruktor mit einem Kontrakt als Übergabeparameter und setzen Sie die benannten Parameter DbcAccessType und DbcCheckTime. ähnelt.
        /// </summary>
        internal static string ExcOnlyOneContract {
            get {
                return ResourceManager.GetString("ExcOnlyOneContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Apekt-Parameter &apos;{0}&apos; kann nicht in Eintrittskontrakte definiert werden da es zu diesem Zeitpunkt keinen Rückgabewert Wert gibt. ähnelt.
        /// </summary>
        internal static string ExcResultAccesNotValidOnMethodAndProperty {
            get {
                return ResourceManager.GetString("ExcResultAccesNotValidOnMethodAndProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Aspekt-Parameter &apos;{0}&apos; darf nicht verwendet werden wenn der Kontrakt auch bei Schreibzugriff (set) geprüft werden soll. ähnelt.
        /// </summary>
        internal static string ExcResultNotValidOnField {
            get {
                return ResourceManager.GetString("ExcResultNotValidOnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie können den Konstruktor mit 4 Übergabeparametern nur an Eigenschaften definieren. ähnelt.
        /// </summary>
        internal static string ExcTooManyContractsDefined {
            get {
                return ResourceManager.GetString("ExcTooManyContractsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden keine vier Kontrakte benötigt, um lediglich ein Lesezugriff (get) bzw. ein Schreibzugriff (set) zu prüfen. ähnelt.
        /// </summary>
        internal static string ExcTooManyContractsOnGetOrSet {
            get {
                return ResourceManager.GetString("ExcTooManyContractsOnGetOrSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Apekt-Parameter &apos;{0}&apos; kann nicht in Kontrakten verwendet werden die an Methoden oder bei Lesezugriff (get) von Eigenschaften, definiert sind. ähnelt.
        /// </summary>
        internal static string ExcValueAccesNotValidOnMethodAndProperty {
            get {
                return ResourceManager.GetString("ExcValueAccesNotValidOnMethodAndProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Aspekt-Parameter &apos;{0}&apos; darf nicht verwendet werden wenn der Kontrakt auch bei Lesezugriff (get) geprüft werden soll. ähnelt.
        /// </summary>
        internal static string ExcValueNotValidOnField {
            get {
                return ResourceManager.GetString("ExcValueNotValidOnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der benannte Parameter DbcAccessType hat keinen Auswirkungen auf Methoden. Bitte löschen Sie den Parameter da Sie sonst andere Entwickler evtl. verwirren. ähnelt.
        /// </summary>
        internal static string ExcWrongDbcAccessTypeUse {
            get {
                return ResourceManager.GetString("ExcWrongDbcAccessTypeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zwei Kontrakte können nur an Felder definiert werden wenn DbcAccessType = Both ist. ähnelt.
        /// </summary>
        internal static string ExcWrongDbcAccessTypeUseOnField {
            get {
                return ResourceManager.GetString("ExcWrongDbcAccessTypeUseOnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der benannte Parameter DbcCheckTime hat keinen Auswirkungen auf Felder. Bitte löschen Sie den Parameter da Sie sonst andere Entwickler evtl. verwirren. ähnelt.
        /// </summary>
        internal static string ExcWrongDbcCheckTimeUse {
            get {
                return ResourceManager.GetString("ExcWrongDbcCheckTimeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zwei Kontrakte können nur an Methoden definiert werden wenn DbcCheckTime = Both ist. ähnelt.
        /// </summary>
        internal static string ExcWrongDbcCheckTimeUseOnMethod {
            get {
                return ResourceManager.GetString("ExcWrongDbcCheckTimeUseOnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zwei Kontrakte können nur an Eigenschaften und Methoden definiert werden wenn DbcCheckTime = Both ist.Wenn Sie einen Kontrakt nur bei Aurtritt oder bei Eintrittmöchten verwenden Sie bitte den Kontrakt mit einem Übergabeparameter. Wenn Sie eine Eigenschaft nur bei Eintritt oder Austriit für get und für set prüfen möchten, benutzen den Konstruktor mit4 Übergabeparameter und übergeben Sie ggf. &apos;null&apos; bzw. string.Empty. ähnelt.
        /// </summary>
        internal static string ExcWrongDbcCheckTimeUseOnMethodAndProperty {
            get {
                return ResourceManager.GetString("ExcWrongDbcCheckTimeUseOnMethodAndProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [old] ähnelt.
        /// </summary>
        internal static string StrAspectParameterOldAccess {
            get {
                return ResourceManager.GetString("StrAspectParameterOldAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [result] ähnelt.
        /// </summary>
        internal static string StrAspectParameterResultAccess {
            get {
                return ResourceManager.GetString("StrAspectParameterResultAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [value] ähnelt.
        /// </summary>
        internal static string StrAspectParameterValueAccess {
            get {
                return ResourceManager.GetString("StrAspectParameterValueAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .Contracts.dll ähnelt.
        /// </summary>
        internal static string StrAssemblyFileExt {
            get {
                return ResourceManager.GetString("StrAssemblyFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckContract ähnelt.
        /// </summary>
        internal static string StrCheckContractMethodName {
            get {
                return ResourceManager.GetString("StrCheckContractMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ContractClass_ ähnelt.
        /// </summary>
        internal static string StrContractClassPrefix {
            get {
                return ResourceManager.GetString("StrContractClassPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ContractMethod_ ähnelt.
        /// </summary>
        internal static string StrContractMethodPrefix {
            get {
                return ResourceManager.GetString("StrContractMethodPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GetOldValues ähnelt.
        /// </summary>
        internal static string StrGetOldPrarameterMethodName {
            get {
                return ResourceManager.GetString("StrGetOldPrarameterMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GetOldValueMethod_ ähnelt.
        /// </summary>
        internal static string StrGetOldValueMethodPrefix {
            get {
                return ResourceManager.GetString("StrGetOldValueMethodPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DesignByContract ähnelt.
        /// </summary>
        internal static string StrNameSpace {
            get {
                return ResourceManager.GetString("StrNameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die contractArguments ähnelt.
        /// </summary>
        internal static string StrParameterContractArguments {
            get {
                return ResourceManager.GetString("StrParameterContractArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die contractKey ähnelt.
        /// </summary>
        internal static string StrParameterContractKey {
            get {
                return ResourceManager.GetString("StrParameterContractKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die exception ähnelt.
        /// </summary>
        internal static string StrParameterException {
            get {
                return ResourceManager.GetString("StrParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die genericTypes ähnelt.
        /// </summary>
        internal static string StrParameterGenericTypes {
            get {
                return ResourceManager.GetString("StrParameterGenericTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die instance ähnelt.
        /// </summary>
        internal static string StrParameterInstance {
            get {
                return ResourceManager.GetString("StrParameterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die methodResult ähnelt.
        /// </summary>
        internal static string StrParameterMethodResult {
            get {
                return ResourceManager.GetString("StrParameterMethodResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oldValues ähnelt.
        /// </summary>
        internal static string StrParameterOldValues {
            get {
                return ResourceManager.GetString("StrParameterOldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .Contracts.pdb ähnelt.
        /// </summary>
        internal static string StrPdbFileExt {
            get {
                return ResourceManager.GetString("StrPdbFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .Contracts.cs ähnelt.
        /// </summary>
        internal static string StrSourceCodeFielExt {
            get {
                return ResourceManager.GetString("StrSourceCodeFielExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        internal static string StrSystemNameSpace {
            get {
                return ResourceManager.GetString("StrSystemNameSpace", resourceCulture);
            }
        }
    }
}
